# This file is used for the development of FerretDB, not for actually running it.
---
version: '3.3'
services:
  # for compatibility testing and mongosh
  mongodb:
    image: mongo:5.0.5
    container_name: ferretdb_mongodb
    ports:
      - 127.0.0.1:37017:27017
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      # Always UTC+05:45. Set to catch timezone problems.
      - TZ=Asia/Kathmandu
  
