# This file is used for the development of MangoDB, not for actually running it.
---
version: '3.8'

services:
  postgres:
    image: postgres:14.0
    container_name: mangodb_postgres
    ports:
      - 127.0.0.1:5432:5432
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mangodb
    volumes:
      - test_db_postgres:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ['CMD', 'psql', '-U', 'postgres', '-l']
      interval: 3s
      timeout: 5s
      retries: 30

  # for compatibility testing and mongosh
  mongodb:
    image: mongo:5.0.3
    container_name: mangodb_mongodb
    ports:
      - 127.0.0.1:37017:27017
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - test_db_mongodb:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'disableTelemetry()']
      interval: 3s
      timeout: 5s
      retries: 30

  test_db:
    image: aleksi/test_db:1.2.0
    container_name: mangodb_test_db
    volumes:
      - test_db_postgres:/test_db/postgresql/pagila:ro
      - test_db_mongodb:/test_db/mongodb/monila:ro

volumes:
  test_db_postgres:
  test_db_mongodb:
