name: go test
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: Test
        run: go test ./... -v
